In [1]:
!pip install liana scanpy anndata numpy pandas matplotlib

Requirement already satisfied: liana in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (1.8.0)
Requirement already satisfied: scanpy in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (1.11.5)
Requirement already satisfied: anndata in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (0.12.19)
Requirement already satisfied: numpy in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (2.4.6)
Requirement already satisfied: pandas in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (2.3.3)
Requirement already satisfied: matplotlib in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (3.11.0)
Requirement already satisfied: docrep>=0.3.1 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from liana) (0.3.2)
Requirement already satisfied: mudata in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from liana) (0.3.9)
Requirement already satisfied: numba in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from liana) (0.66.0)
Requirement already satisfied: plotnine>=0.10.1 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from liana) (0.15.7)
Requirement already satisfied: session-info2 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from liana) (0.4.1)
Requirement already satisfied: tqdm>=4.0 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from liana) (4.68.3)
Requirement already satisfied: h5py>=3.7.0 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scanpy) (3.16.0)
Requirement already satisfied: joblib in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scanpy) (1.5.3)
Requirement already satisfied: legacy-api-wrap>=1.4.1 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scanpy) (1.5)
Requirement already satisfied: natsort in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scanpy) (8.4.0)
Requirement already satisfied: networkx>=2.7.1 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scanpy) (3.6.1)
Requirement already satisfied: packaging>=21.3 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scanpy) (26.0)
Requirement already satisfied: patsy!=1.0.0 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scanpy) (1.0.2)
Requirement already satisfied: pynndescent>=0.5.13 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scanpy) (0.6.0)
Requirement already satisfied: scikit-learn>=1.1.3 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scanpy) (1.9.0)
Requirement already satisfied: scipy>=1.8.1 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scanpy) (1.17.1)
Requirement already satisfied: seaborn>=0.13.2 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scanpy) (0.13.2)
Requirement already satisfied: statsmodels>=0.14.5 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scanpy) (0.14.6)
Requirement already satisfied: typing-extensions in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scanpy) (4.16.0)
Requirement already satisfied: umap-learn>=0.5.6 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scanpy) (0.5.12)
Requirement already satisfied: array-api-compat>=1.7.1 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from anndata) (1.15.0)
Requirement already satisfied: scverse-misc>=0.0.3 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from anndata) (0.0.3)
Requirement already satisfied: zarr!=3.0.*,>=2.18.7 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from anndata) (3.1.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pillow>=9 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from docrep>=0.3.1->liana) (1.17.0)
Requirement already satisfied: llvmlite<0.49,>=0.48.0dev0 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from numba->liana) (0.48.0)
Requirement already satisfied: mizani~=0.14.0 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from plotnine>=0.10.1->liana) (0.14.4)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scikit-learn>=1.1.3->scanpy) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from scikit-learn>=1.1.3->scanpy) (3.6.0)
Requirement already satisfied: colorama in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from tqdm>=4.0->liana) (0.4.6)
Requirement already satisfied: donfig>=0.8 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from zarr!=3.0.*,>=2.18.7->anndata) (0.8.1.post1)
Requirement already satisfied: google-crc32c>=1.5 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from zarr!=3.0.*,>=2.18.7->anndata) (1.8.0)
Requirement already satisfied: numcodecs>=0.14 in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from zarr!=3.0.*,>=2.18.7->anndata) (0.16.5)
Requirement already satisfied: pyyaml in C:\Users\Lenovo\miniconda3\envs\brca\Lib\site-packages (from donfig>=0.8->zarr!=3.0.*,>=2.18.7->anndata) (6.0.3)

In [2]:
import scanpy as sc
import liana as li
import pandas as pd
import numpy as np

In [6]:
import anndata as ad

f = ad.read_h5ad(
    r"C:\BRCA\BRCA Project\data\IntegratedAtlas.h5ad",
    backed="r"
)

f

AnnData object with n_obs × n_vars = 621200 × 37389 backed at 'C:\\BRCA\\BRCA Project\\data\\IntegratedAtlas.h5ad'
    obs: 'tissue_ontology_term_id', 'tissue_type', 'assay_ontology_term_id', 'disease_ontology_term_id', 'cell_type_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'development_stage_ontology_term_id', 'sex_ontology_term_id', 'donor_id', 'suspension_type', 'grade', 'author_cell_type', 'batch', 'is_primary_data', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'batch_condition', 'citation', 'default_embedding', 'is_pre_analysis', 'organism', 'organism_ontology_term_id', 'schema_reference', 'schema_version', 'title'
    obsm: 'X_rpca', 'X_umap'

In [7]:
adata.obs["donor_id"].value_counts().head()

donor_id
pal_Patient 0177    18812
pal_Patient 0176    17155
pal_Patient 0135    14709
TBB129              13340
TBB338              12893
Name: count, dtype: int64

In [8]:
adata.obs["cell_type"].value_counts().head(20)

cell_type
malignant cell                                                              242613
fibroblast                                                                   45702
macrophage                                                                   44437
effector memory CD8-positive, alpha-beta T cell                              29592
effector memory CD4-positive, alpha-beta T cell                              23696
natural killer cell                                                          23508
memory B cell                                                                21190
CD4-positive, CD25-positive, CCR4-positive, alpha-beta regulatory T cell     19802
naive T cell                                                                 18117
IgG plasma cell                                                              17824
exhausted T cell                                                             17359
CD8-positive, alpha-beta regulatory T cell                                   14182
conventional dendritic cell                                                  12855
endothelial cell                                                             11927
T follicular helper cell                                                     11838
vein endothelial cell                                                        10318
vascular associated smooth muscle cell                                        9172
endothelial cell of vascular tree                                             8749
cycling T cell                                                                6729
myofibroblast cell                                                            6689
Name: count, dtype: int64

In [10]:
donor = adata.obs["donor_id"].unique()[0]

adata_p = adata[adata.obs["donor_id"] == donor].to_memory()

adata_p

AnnData object with n_obs × n_vars = 6176 × 37389
    obs: 'tissue_ontology_term_id', 'tissue_type', 'assay_ontology_term_id', 'disease_ontology_term_id', 'cell_type_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'development_stage_ontology_term_id', 'sex_ontology_term_id', 'donor_id', 'suspension_type', 'grade', 'author_cell_type', 'batch', 'is_primary_data', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'batch_condition', 'citation', 'default_embedding', 'is_pre_analysis', 'organism', 'organism_ontology_term_id', 'schema_reference', 'schema_version', 'title'
    obsm: 'X_rpca', 'X_umap'

In [11]:
adata_p.obs["cell_type"].value_counts()

cell_type
effector memory CD4-positive, alpha-beta T cell                             1310
naive T cell                                                                1269
effector memory CD8-positive, alpha-beta T cell                              875
malignant cell                                                               706
natural killer cell                                                          360
memory B cell                                                                322
T follicular helper cell                                                     313
CD4-positive, CD25-positive, CCR4-positive, alpha-beta regulatory T cell     310
fibroblast                                                                   186
macrophage                                                                   101
CD8-positive, alpha-beta regulatory T cell                                    89
endothelial cell of vascular tree                                             77
cycling T cell                                                                40
conventional dendritic cell                                                   39
plasmacytoid dendritic cell                                                   39
exhausted T cell                                                              36
endothelial cell                                                              35
vein endothelial cell                                                         25
endothelial cell of artery                                                    18
vascular associated smooth muscle cell                                         8
myofibroblast cell                                                             6
cycling macrophage                                                             6
pericyte                                                                       5
myeloid dendritic cell                                                         1
Name: count, dtype: int64

In [12]:
import liana as li

In [14]:
adata_p.var.head()

,feature_is_filtered,feature_name,feature_reference,feature_biotype,feature_length,feature_type
ENSG00000286448,False,ENSG00000286448,NCBITaxon:9606,gene,728,lncRNA
ENSG00000225880,False,LINC00115,NCBITaxon:9606,gene,874,lncRNA
ENSG00000230368,False,FAM41C,NCBITaxon:9606,gene,919,lncRNA
ENSG00000187634,False,SAMD11,NCBITaxon:9606,gene,1731,protein_coding
ENSG00000188976,False,NOC2L,NCBITaxon:9606,gene,1244,protein_coding

In [15]:
adata_p.var["feature_name"].head()

ENSG00000286448    ENSG00000286448
ENSG00000225880          LINC00115
ENSG00000230368             FAM41C
ENSG00000187634             SAMD11
ENSG00000188976              NOC2L
Name: feature_name, dtype: category
Categories (37361, object): ['A1BG', 'A1BG-AS1', 'A1CF', 'A2M', ..., 'ZZEF1', 'ZZZ3', 'hsa-mir-1253', 'hsa-mir-423']

In [16]:
adata_p.var_names = adata_p.var["feature_name"]

In [17]:
adata_p.X

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 5871242 stored elements and shape (6176, 37389)>

In [18]:
adata_p.var_names = adata_p.var["feature_name"]

In [19]:
adata_p.var_names[:5]

Index(['ENSG00000286448', 'LINC00115', 'FAM41C', 'SAMD11', 'NOC2L'], dtype='object', name='feature_name')

In [20]:
import scanpy as sc

sc.pp.normalize_total(adata_p, target_sum=1e4)
sc.pp.log1p(adata_p)

In [22]:
adata_p.raw = adata_p

In [26]:
import scanpy as sc

adata_p.X = adata_p.X.copy()

In [27]:
adata_p.raw = adata_p

In [31]:
import liana.resource as lr

lr_db = lr.select_resource("consensus")
lr_db.head()

   ligand receptor
0  LGALS9    PTPRC
1  LGALS9      MET
2  LGALS9     CD44
3  LGALS9     LRP1
4  LGALS9     CD47

In [32]:
import pandas as pd

expr = adata_p.to_df()
expr["cell_type"] = adata_p.obs["cell_type"].values

mean_expr = expr.groupby("cell_type").mean()
mean_expr.shape

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_24128\4244700143.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

(24, 37389)

In [36]:
cell_types = mean_expr.index.tolist()

In [37]:
mean_expr_aligned = mean_expr.copy()
mean_expr_aligned = mean_expr_aligned.loc[cell_types]

In [38]:
scores = []

for _, row in lig_rec.iterrows():
    lig = row["ligand"]
    rec = row["receptor"]

    if lig in mean_expr_aligned.columns and rec in mean_expr_aligned.columns:

        lig_vec = mean_expr_aligned[lig].values.astype(float)
        rec_vec = mean_expr_aligned[rec].values.astype(float)

        if lig_vec.shape == rec_vec.shape:

            score = float((lig_vec * rec_vec).sum())
            scores.append([lig, rec, score])

ccc_df = pd.DataFrame(scores, columns=["ligand", "receptor", "score"])
ccc_df.sort_values("score", ascending=False).head(10)

      ligand  receptor      score
2773     VIM      CD44  58.513568
78     HLA-B      CD3D  50.588818
3032   HMGB1     CXCR4  45.188863
119      APP      CD74  35.022281
1432  LGALS1     PTPRC  26.619255
2514   TIMP1      CD63  26.476228
1431  LGALS1     ITGB1  25.974649
1623     MIF  TNFRSF14  24.714781
77     HLA-B      CD8A  23.816556
170    HLA-C      CD8A  22.594716