In [4]:
import scanpy as sc

adata = sc.read_h5ad("C:/BRCA/BRCA Project/data/IntegratedAtlas.h5ad")

print(adata)

AnnData object with n_obs × n_vars = 621200 × 37389
    obs: 'tissue_ontology_term_id', 'tissue_type', 'assay_ontology_term_id', 'disease_ontology_term_id', 'cell_type_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'development_stage_ontology_term_id', 'sex_ontology_term_id', 'donor_id', 'suspension_type', 'grade', 'author_cell_type', 'batch', 'is_primary_data', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'batch_condition', 'citation', 'default_embedding', 'is_pre_analysis', 'organism', 'organism_ontology_term_id', 'schema_reference', 'schema_version', 'title'
    obsm: 'X_rpca', 'X_umap'

In [2]:
print("Hello World")

Hello World

In [5]:
import pandas as pd

xls = pd.ExcelFile(
    r"C:\BRCA\BRCA Project\data\integratedatlas_supplemental_files\SuppTable1.xlsx"
)

print(xls.sheet_names)

['A-PAM50', 'B-InferCNV', 'C-Signatures', 'D-Survival', 'E-Metabric']

In [6]:
for sheet in xls.sheet_names:

    df = pd.read_excel(xls, sheet_name=sheet)

    print("=" * 80)
    print(sheet)
    print(df.shape)
    print(df.columns.tolist())

================================================================================
A-PAM50
(138, 6)
['donor_id', 'Basal', 'Her2', 'LumA', 'LumB', 'Normal']
================================================================================
B-InferCNV
(9, 2)
['InferCNV empirical malignancy cutoffs', 'Unnamed: 1']
================================================================================
C-Signatures
(7, 4)
['Publication name', 'PMID', 'Source', 'Signature Type ']
================================================================================
D-Survival
(96, 9)
['Combined', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8']
================================================================================
E-Metabric
(38, 11)
['Positively Associated with Grade in Atlas', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Negatively Associated with Grade in Atlas', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10']

In [7]:
for sheet in xls.sheet_names:

    df = pd.read_excel(xls, sheet_name=sheet)

    print("=" * 80)
    print(sheet)
    display(df.head())

================================================================================
A-PAM50

           donor_id     Basal      Her2  LumA      LumB  Normal
0  BC17086-12-Tumor  0.254329  0.429654   0.0  0.316017     0.0
1  BC17086-24-Tumor  0.479841  0.333790   0.0  0.186369     0.0
2  BC17086-25-Tumor  0.044725  0.482418   0.0  0.472856     0.0
3  BC17086-35-Tumor  0.000000  0.567416   0.0  0.432584     0.0
4       BC258-Tumor  0.000000  0.487568   0.0  0.512432     0.0

================================================================================
B-InferCNV

  InferCNV empirical malignancy cutoffs    Unnamed: 1
0                                 Batch  95% Quantile
1                           bassez_2021        1.0064
2                              gao_2021        1.0063
3                              liu_2023        1.0069
4                              pal_2021        1.0082

================================================================================
C-Signatures

,Publication name,PMID,Source,Signature Type
0,Single-cell resolution characterization of mye...,38972873,Pan-cancer,Myeloid
1,Pan-cancer T cell atlas links a cellular stres...,37248301,Pan-cancer,T Cell
2,Integration of Pan-Cancer Single-Cell and Spat...,38225927,Pan-cancer,Stromal
3,A spatially resolved single-cell genomic atlas...,37380767,HBCA,"Immune, Epithelial, Stromal"
4,The Molecular Signatures Database (MSigDB) hal...,26771021,mSigDB,Hallmarks

================================================================================
D-Survival

,Combined,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Compartment,Annotation,TCGA,NaN,METABRIC,NaN,SCANB,NaN,Fisher’s p-value
1,NaN,NaN,Hazard,Adj. p-value,Hazard,Adj. p-value,Hazard,Adj. p-value,NaN
2,Epithelial,0,0.44,0.001,NaN,NaN,NaN,NaN,NaN
3,NaN,14,0.42,0.156,NaN,NaN,NaN,NaN,NaN
4,NaN,17,0.48,0.003,0.88,0.317,NaN,NaN,NaN

================================================================================
E-Metabric

,Positively Associated with Grade in Atlas,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Negatively Associated with Grade in Atlas,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,CD8_tex_score ~ GRADE + Pam50_SUBTYPE + AGE_AT...,NaN,NaN,NaN,NaN,NaN,Mac_ES_score ~ GRADE + Pam50_SUBTYPE + AGE_AT_...,NaN,NaN,NaN,NaN
1,NaN,Estimate,Std. Error,t value,Pr(>|t|),NaN,NaN,Estimate,Std. Error,t value,Pr(>|t|)
2,(Intercept),0.158888,0.051172,3.104984,0.00193,NaN,(Intercept),-0.001082,0.037448,-0.028901,0.976947
3,GRADE2,0.090436,0.030508,2.964318,0.00307,NaN,GRADE2,0.035075,0.022326,1.571021,0.116338
4,GRADE3,0.169507,0.031851,5.321927,0.0,NaN,GRADE3,0.043229,0.023309,1.854608,0.063801

In [8]:
for sheet in xls.sheet_names:

    df = pd.read_excel(xls, sheet_name=sheet)

    print("=" * 80)
    print(sheet)

    missing = (
        df.isna()
        .sum()
        .sort_values(ascending=False)
    )

    print(missing[missing > 0])

================================================================================
A-PAM50
Series([], dtype: int64)
================================================================================
B-InferCNV
Series([], dtype: int64)
================================================================================
C-Signatures
Series([], dtype: int64)
================================================================================
D-Survival
Combined      71
Unnamed: 8    40
Unnamed: 5    32
Unnamed: 7    30
Unnamed: 4    27
Unnamed: 6    25
Unnamed: 3    20
Unnamed: 1    18
Unnamed: 2    15
dtype: int64
================================================================================
E-Metabric
Unnamed: 5                                   38
Negatively Associated with Grade in Atlas    16
Unnamed: 8                                   16
Unnamed: 9                                   16
Unnamed: 10                                  16
Unnamed: 7                                   16
Positively Associated with Grade in Atlas     5
Unnamed: 2                                    5
Unnamed: 1                                    5
Unnamed: 3                                    5
Unnamed: 4                                    5
dtype: int64